#!/usr/bin/env python3
"""Rebuild bundled ICU converter resources from the pinned icu-data submodule.

Manual maintainer tool; requires makeconv, pkgdata and icupkg. Normal builds
use the checked-in header and do not run this tool or access the network.
"""
import json
import re
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / 'src/data-types/charconv-icu'
ICU_DATA = ROOT / 'dependencies/submodules/icu-data'
PACKAGE = 'libetpan_charsets'


def run(*args):
    subprocess.run(args, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                   timeout=60)


def main():
    manifest = json.loads((DATA / 'manifest.json').read_text())
    if not (ICU_DATA / 'charset/data/ucm').is_dir():
        raise RuntimeError('Initialize dependencies/submodules/icu-data with '
                           'git submodule update --init before rebuilding data')
    revision = subprocess.check_output(
        ['git', '-C', str(ICU_DATA), 'rev-parse', 'HEAD'], text=True).strip()
    if revision != manifest['revision']:
        raise RuntimeError('Review and update manifest icu-data baseline before rebuilding data')
    sources = {}
    for row in manifest['tables']:
        source = ICU_DATA / row['upstream_path']
        if source.name != row['file'] or not source.is_file():
            raise RuntimeError('Missing or inconsistent ICU mapping: ' + str(source))
        sources[row['file']] = source
    version = subprocess.check_output(['pkg-config', '--modversion', 'icu-uc'], text=True).strip()
    if version != manifest['icu_generation_version']:
        raise RuntimeError('Review and update manifest ICU baseline before rebuilding data')
    # CoreFoundation lacks these two reviewed email converters. Keep their
    # small UTF-8 fallback tables independent of an ICU library dependency.
    legacy = ['/* Generated from pinned icu-data UCMs; see LICENSE and manifest.json. */',
              'static const struct { const char * name; unsigned short unicode[256]; }',
              'apple_legacy_charsets[] = {']
    for row in manifest['tables']:
        if row['group'] not in ('VISCII', 'KOI8-T'):
            continue
        values = [0xffff] * 256
        for cp, byte in re.findall(r'<U([0-9A-Fa-f]+)>\s+\\x([0-9A-Fa-f]{2})\s+\|0', sources[row['file']].read_text()):
            value, index = int(cp, 16), int(byte, 16)
            assert value < 0xffff and values[index] == 0xffff
            values[index] = value
        legacy.append('  { %s, {' % json.dumps(row['group']))
        legacy += ['    ' + ', '.join('0x%04x' % v for v in values[i:i+16]) + ','
                   for i in range(0, 256, 16)]
        legacy.append('  } },')
    (DATA / 'apple-legacy.h').write_text('\n'.join(legacy + ['};', '']))
    alias_rows = {}
    for row in manifest['verified_aliases']:
        for name in row['names']:
            alias_rows[name.lower()] = (row['target'], 0)
    for row in manifest['tables']:
        for name in row['names']:
            alias_rows[name.lower()] = (Path(row['file']).stem, 1)
    for row in manifest['ambiguous_aliases']:
        alias_rows[row['name'].lower()] = (row['target'], 0)
    aliases = ['/* Reviewed alias/data selections. See charconv-icu/manifest.json. */',
               'static const struct { const char * name; const char * target; int packaged; }',
               'charconv_icu_aliases[] = {']
    for name, (target, packaged) in sorted(alias_rows.items()):
        aliases.append('  { %s, %s, %d },' % (json.dumps(name), json.dumps(target), packaged))
    (DATA / 'aliases.h').write_text('\n'.join(aliases + ['};', '']))
    with tempfile.TemporaryDirectory(prefix='libetpan-icu-data-') as directory:
        work = Path(directory)
        names = sorted(sources)
        for name in names:
            run('makeconv', '-d', str(work), str(sources[name]))
        listing = work / 'files.txt'
        listing.write_text(''.join(Path(n).stem + '.cnv\n' for n in names))
        run('pkgdata', '-p', PACKAGE, '-m', 'common', '-s', str(work),
            '-d', str(work), str(listing))
        original = work / (PACKAGE + '.dat')
        result = ['/* Generated by tests/generate-charconv-icu-data.py. */',
                  '/* ICU mapping data: see charconv-icu/LICENSE and manifest.json. */']
        for endian, flag in [('big', '-tb'), ('little', '-tl')]:
            (work / endian).mkdir()
            target = work / endian / (PACKAGE + '.dat')
            run('icupkg', flag, str(original), str(target))
            binary = target.read_bytes()
            result += ['#if U_IS_BIG_ENDIAN' if endian == 'big' else '#else',
                       'static const union {', '  long double alignment;',
                       '  unsigned char bytes[%d];' % len(binary),
                       '} charconv_icu_data = { .bytes = {']
            result += ['  ' + ', '.join('0x%02x' % b for b in binary[i:i+16]) + ','
                       for i in range(0, len(binary), 16)]
            result += ['} };']
        result += ['#endif', '']
        (DATA / 'data.h').write_text('\n'.join(result))
        print('Generated', DATA / 'data.h', 'from', len(names), 'tables')


if __name__ == '__main__':
    main()
