/*
 * libEtPan! -- a mail stuff library
 */

#ifndef MAILACTIVESYNC_CODES_H

#define MAILACTIVESYNC_CODES_H

#ifdef __cplusplus
extern "C" {
#endif

#include <libetpan/libetpan-config.h>

#include <stdint.h>

#define MAILACTIVESYNC_WBXML_SWITCH_PAGE 0x00
#define MAILACTIVESYNC_WBXML_END         0x01
#define MAILACTIVESYNC_WBXML_ENTITY      0x02
#define MAILACTIVESYNC_WBXML_STR_I       0x03
#define MAILACTIVESYNC_WBXML_LITERAL     0x04
#define MAILACTIVESYNC_WBXML_STR_T       0x83
#define MAILACTIVESYNC_WBXML_OPAQUE      0xC3

#define MAILACTIVESYNC_WBXML_HAS_CONTENT 0x40
#define MAILACTIVESYNC_WBXML_HAS_ATTRS   0x80
#define MAILACTIVESYNC_WBXML_TOKEN_MASK  0x3F

#define MAILACTIVESYNC_WBXML_VERSION     0x03
#define MAILACTIVESYNC_WBXML_PUBLIC_ID   0x01
#define MAILACTIVESYNC_WBXML_CHARSET     0x6A

enum {
  MAILACTIVESYNC_CP_AIRSYNC = 0,
  MAILACTIVESYNC_CP_EMAIL = 2,
  MAILACTIVESYNC_CP_MOVE = 5,
  MAILACTIVESYNC_CP_GETITEMESTIMATE = 6,
  MAILACTIVESYNC_CP_FOLDERHIERARCHY = 7,
  MAILACTIVESYNC_CP_PING = 13,
  MAILACTIVESYNC_CP_PROVISION = 14,
  MAILACTIVESYNC_CP_AIRSYNCBASE = 17,
  MAILACTIVESYNC_CP_SETTINGS = 18,
  MAILACTIVESYNC_CP_ITEMOPERATIONS = 20,
  MAILACTIVESYNC_CP_COMPOSEMAIL = 21
};

enum {
  MAILACTIVESYNC_AIRSYNC_SYNC = 0x05,
  MAILACTIVESYNC_AIRSYNC_RESPONSES = 0x06,
  MAILACTIVESYNC_AIRSYNC_ADD = 0x07,
  MAILACTIVESYNC_AIRSYNC_CHANGE = 0x08,
  MAILACTIVESYNC_AIRSYNC_DELETE = 0x09,
  MAILACTIVESYNC_AIRSYNC_FETCH = 0x0A,
  MAILACTIVESYNC_AIRSYNC_SYNC_KEY = 0x0B,
  MAILACTIVESYNC_AIRSYNC_CLIENT_ID = 0x0C,
  MAILACTIVESYNC_AIRSYNC_SERVER_ID = 0x0D,
  MAILACTIVESYNC_AIRSYNC_STATUS = 0x0E,
  MAILACTIVESYNC_AIRSYNC_COLLECTION = 0x0F,
  MAILACTIVESYNC_AIRSYNC_CLASS = 0x10,
  MAILACTIVESYNC_AIRSYNC_COLLECTION_ID = 0x12,
  MAILACTIVESYNC_AIRSYNC_GET_CHANGES = 0x13,
  MAILACTIVESYNC_AIRSYNC_MORE_AVAILABLE = 0x14,
  MAILACTIVESYNC_AIRSYNC_WINDOW_SIZE = 0x15,
  MAILACTIVESYNC_AIRSYNC_COMMANDS = 0x16,
  MAILACTIVESYNC_AIRSYNC_OPTIONS = 0x17,
  MAILACTIVESYNC_AIRSYNC_FILTER_TYPE = 0x18,
  MAILACTIVESYNC_AIRSYNC_CONFLICT = 0x1B,
  MAILACTIVESYNC_AIRSYNC_COLLECTIONS = 0x1C,
  MAILACTIVESYNC_AIRSYNC_APPLICATION_DATA = 0x1D,
  MAILACTIVESYNC_AIRSYNC_DELETES_AS_MOVES = 0x1E,
  MAILACTIVESYNC_AIRSYNC_SUPPORTED = 0x20,
  MAILACTIVESYNC_AIRSYNC_SOFT_DELETE = 0x21,
  MAILACTIVESYNC_AIRSYNC_MIME_SUPPORT = 0x22,
  MAILACTIVESYNC_AIRSYNC_MIME_TRUNCATION = 0x23,
  MAILACTIVESYNC_AIRSYNC_WAIT = 0x24,
  MAILACTIVESYNC_AIRSYNC_LIMIT = 0x25,
  MAILACTIVESYNC_AIRSYNC_PARTIAL = 0x26,
  MAILACTIVESYNC_AIRSYNC_CONVERSATION_MODE = 0x27,
  MAILACTIVESYNC_AIRSYNC_MAX_ITEMS = 0x28,
  MAILACTIVESYNC_AIRSYNC_HEARTBEAT_INTERVAL = 0x29
};

enum {
  MAILACTIVESYNC_EMAIL_DATE_RECEIVED = 0x0F,
  MAILACTIVESYNC_EMAIL_DISPLAY_TO = 0x11,
  MAILACTIVESYNC_EMAIL_IMPORTANCE = 0x12,
  MAILACTIVESYNC_EMAIL_MESSAGE_CLASS = 0x13,
  MAILACTIVESYNC_EMAIL_SUBJECT = 0x14,
  MAILACTIVESYNC_EMAIL_READ = 0x15,
  MAILACTIVESYNC_EMAIL_TO = 0x16,
  MAILACTIVESYNC_EMAIL_CC = 0x17,
  MAILACTIVESYNC_EMAIL_FROM = 0x18,
  MAILACTIVESYNC_EMAIL_REPLY_TO = 0x19,
  MAILACTIVESYNC_EMAIL_FLAG = 0x1B
};

enum {
  MAILACTIVESYNC_MOVE_MOVES = 0x05,
  MAILACTIVESYNC_MOVE_MOVE = 0x06,
  MAILACTIVESYNC_MOVE_SRCMSGID = 0x07,
  MAILACTIVESYNC_MOVE_SRCFLDID = 0x08,
  MAILACTIVESYNC_MOVE_DSTFLDID = 0x09,
  MAILACTIVESYNC_MOVE_RESPONSE = 0x0A,
  MAILACTIVESYNC_MOVE_STATUS = 0x0B,
  MAILACTIVESYNC_MOVE_DSTMSGID = 0x0C
};

enum {
  MAILACTIVESYNC_GETITEMESTIMATE_GET_ITEM_ESTIMATE = 0x05,
  MAILACTIVESYNC_GETITEMESTIMATE_VERSION = 0x06,
  MAILACTIVESYNC_GETITEMESTIMATE_COLLECTIONS = 0x07,
  MAILACTIVESYNC_GETITEMESTIMATE_COLLECTION = 0x08,
  MAILACTIVESYNC_GETITEMESTIMATE_CLASS = 0x09,
  MAILACTIVESYNC_GETITEMESTIMATE_COLLECTION_ID = 0x0A,
  MAILACTIVESYNC_GETITEMESTIMATE_DATE_TIME = 0x0B,
  MAILACTIVESYNC_GETITEMESTIMATE_ESTIMATE = 0x0C,
  MAILACTIVESYNC_GETITEMESTIMATE_RESPONSE = 0x0D,
  MAILACTIVESYNC_GETITEMESTIMATE_STATUS = 0x0E
};

enum {
  MAILACTIVESYNC_FOLDER_DISPLAY_NAME = 0x07,
  MAILACTIVESYNC_FOLDER_SERVER_ID = 0x08,
  MAILACTIVESYNC_FOLDER_PARENT_ID = 0x09,
  MAILACTIVESYNC_FOLDER_TYPE = 0x0A,
  MAILACTIVESYNC_FOLDER_STATUS = 0x0C,
  MAILACTIVESYNC_FOLDER_CHANGES = 0x0E,
  MAILACTIVESYNC_FOLDER_ADD = 0x0F,
  MAILACTIVESYNC_FOLDER_DELETE = 0x10,
  MAILACTIVESYNC_FOLDER_UPDATE = 0x11,
  MAILACTIVESYNC_FOLDER_SYNC_KEY = 0x12,
  MAILACTIVESYNC_FOLDER_FOLDER_CREATE = 0x13,
  MAILACTIVESYNC_FOLDER_FOLDER_DELETE = 0x14,
  MAILACTIVESYNC_FOLDER_FOLDER_UPDATE = 0x15,
  MAILACTIVESYNC_FOLDER_FOLDER_SYNC = 0x16,
  MAILACTIVESYNC_FOLDER_COUNT = 0x17
};

enum {
  MAILACTIVESYNC_PING_PING = 0x05,
  MAILACTIVESYNC_PING_STATUS = 0x07,
  MAILACTIVESYNC_PING_HEARTBEAT_INTERVAL = 0x08,
  MAILACTIVESYNC_PING_FOLDERS = 0x09,
  MAILACTIVESYNC_PING_FOLDER = 0x0A,
  MAILACTIVESYNC_PING_ID = 0x0B,
  MAILACTIVESYNC_PING_CLASS = 0x0C,
  MAILACTIVESYNC_PING_MAX_FOLDERS = 0x0D
};

enum {
  MAILACTIVESYNC_PROVISION_PROVISION = 0x05,
  MAILACTIVESYNC_PROVISION_POLICIES = 0x06,
  MAILACTIVESYNC_PROVISION_POLICY = 0x07,
  MAILACTIVESYNC_PROVISION_POLICY_TYPE = 0x08,
  MAILACTIVESYNC_PROVISION_POLICY_KEY = 0x09,
  MAILACTIVESYNC_PROVISION_DATA = 0x0A,
  MAILACTIVESYNC_PROVISION_STATUS = 0x0B,
  MAILACTIVESYNC_PROVISION_REMOTE_WIPE = 0x0C,
  MAILACTIVESYNC_PROVISION_EAS_PROVISION_DOC = 0x0D
};

enum {
  MAILACTIVESYNC_AIRSYNCBASE_BODY_PREFERENCE = 0x05,
  MAILACTIVESYNC_AIRSYNCBASE_TYPE = 0x06,
  MAILACTIVESYNC_AIRSYNCBASE_TRUNCATION_SIZE = 0x07,
  MAILACTIVESYNC_AIRSYNCBASE_ALL_OR_NONE = 0x08,
  MAILACTIVESYNC_AIRSYNCBASE_BODY = 0x0A,
  MAILACTIVESYNC_AIRSYNCBASE_DATA = 0x0B,
  MAILACTIVESYNC_AIRSYNCBASE_ESTIMATED_DATA_SIZE = 0x0C,
  MAILACTIVESYNC_AIRSYNCBASE_TRUNCATED = 0x0D,
  MAILACTIVESYNC_AIRSYNCBASE_ATTACHMENTS = 0x0E,
  MAILACTIVESYNC_AIRSYNCBASE_ATTACHMENT = 0x0F,
  MAILACTIVESYNC_AIRSYNCBASE_DISPLAY_NAME = 0x10,
  MAILACTIVESYNC_AIRSYNCBASE_FILE_REFERENCE = 0x11,
  MAILACTIVESYNC_AIRSYNCBASE_METHOD = 0x12,
  MAILACTIVESYNC_AIRSYNCBASE_CONTENT_ID = 0x13,
  MAILACTIVESYNC_AIRSYNCBASE_CONTENT_LOCATION = 0x14,
  MAILACTIVESYNC_AIRSYNCBASE_IS_INLINE = 0x15,
  MAILACTIVESYNC_AIRSYNCBASE_NATIVE_BODY_TYPE = 0x16,
  MAILACTIVESYNC_AIRSYNCBASE_CONTENT_TYPE = 0x17,
  MAILACTIVESYNC_AIRSYNCBASE_PREVIEW = 0x18
};

enum {
  MAILACTIVESYNC_SETTINGS_SETTINGS = 0x05,
  MAILACTIVESYNC_SETTINGS_STATUS = 0x06,
  MAILACTIVESYNC_SETTINGS_GET = 0x07,
  MAILACTIVESYNC_SETTINGS_SET = 0x08,
  MAILACTIVESYNC_SETTINGS_DEVICE_INFORMATION = 0x16,
  MAILACTIVESYNC_SETTINGS_MODEL = 0x17,
  MAILACTIVESYNC_SETTINGS_IMEI = 0x18,
  MAILACTIVESYNC_SETTINGS_FRIENDLY_NAME = 0x19,
  MAILACTIVESYNC_SETTINGS_OS = 0x1A,
  MAILACTIVESYNC_SETTINGS_OS_LANGUAGE = 0x1B,
  MAILACTIVESYNC_SETTINGS_PHONE_NUMBER = 0x1C,
  MAILACTIVESYNC_SETTINGS_USER_AGENT = 0x20,
  MAILACTIVESYNC_SETTINGS_MOBILE_OPERATOR = 0x22
};

enum {
  MAILACTIVESYNC_ITEMOPERATIONS_ITEM_OPERATIONS = 0x05,
  MAILACTIVESYNC_ITEMOPERATIONS_FETCH = 0x06,
  MAILACTIVESYNC_ITEMOPERATIONS_STORE = 0x07,
  MAILACTIVESYNC_ITEMOPERATIONS_OPTIONS = 0x08,
  MAILACTIVESYNC_ITEMOPERATIONS_RANGE = 0x09,
  MAILACTIVESYNC_ITEMOPERATIONS_TOTAL = 0x0A,
  MAILACTIVESYNC_ITEMOPERATIONS_PROPERTIES = 0x0B,
  MAILACTIVESYNC_ITEMOPERATIONS_DATA = 0x0C,
  MAILACTIVESYNC_ITEMOPERATIONS_STATUS = 0x0D,
  MAILACTIVESYNC_ITEMOPERATIONS_RESPONSE = 0x0E,
  MAILACTIVESYNC_ITEMOPERATIONS_VERSION = 0x0F,
  MAILACTIVESYNC_ITEMOPERATIONS_SCHEMA = 0x10,
  MAILACTIVESYNC_ITEMOPERATIONS_PART = 0x11,
  MAILACTIVESYNC_ITEMOPERATIONS_EMPTY_FOLDER_CONTENTS = 0x12,
  MAILACTIVESYNC_ITEMOPERATIONS_DELETE_SUB_FOLDERS = 0x13,
  MAILACTIVESYNC_ITEMOPERATIONS_MOVE = 0x16,
  MAILACTIVESYNC_ITEMOPERATIONS_DSTFLDID = 0x17
};

enum {
  MAILACTIVESYNC_COMPOSEMAIL_SEND_MAIL = 0x05,
  MAILACTIVESYNC_COMPOSEMAIL_SMART_FORWARD = 0x06,
  MAILACTIVESYNC_COMPOSEMAIL_SMART_REPLY = 0x07,
  MAILACTIVESYNC_COMPOSEMAIL_SAVE_IN_SENT_ITEMS = 0x08,
  MAILACTIVESYNC_COMPOSEMAIL_REPLACE_MIME = 0x09,
  MAILACTIVESYNC_COMPOSEMAIL_SOURCE = 0x0B,
  MAILACTIVESYNC_COMPOSEMAIL_FOLDER_ID = 0x0C,
  MAILACTIVESYNC_COMPOSEMAIL_ITEM_ID = 0x0D,
  MAILACTIVESYNC_COMPOSEMAIL_LONG_ID = 0x0E,
  MAILACTIVESYNC_COMPOSEMAIL_INSTANCE_ID = 0x0F,
  MAILACTIVESYNC_COMPOSEMAIL_MIME = 0x10,
  MAILACTIVESYNC_COMPOSEMAIL_CLIENT_ID = 0x11,
  MAILACTIVESYNC_COMPOSEMAIL_STATUS = 0x12,
  MAILACTIVESYNC_COMPOSEMAIL_ACCOUNT_ID = 0x13
};

struct mailactivesync_wbxml_token_info {
  uint8_t code_page;
  uint8_t token;
  const char * name;
};

LIBETPAN_EXPORT
const char * mailactivesync_wbxml_tag_name(uint8_t code_page,
    uint8_t token);

LIBETPAN_EXPORT
int mailactivesync_wbxml_tag_lookup(const char * name,
    uint8_t * code_page,
    uint8_t * token);

#ifdef __cplusplus
}
#endif

#endif
