/*
 * libEtPan! -- a mail stuff library
 */

#ifndef MAILACTIVESYNC_CODES_H

#define MAILACTIVESYNC_CODES_H

#ifdef __cplusplus
extern "C" {
#endif

#include <libetpan/libetpan-config.h>

#include <stdint.h>

#define MAILACTIVESYNC_WBXML_SWITCH_PAGE 0x00
#define MAILACTIVESYNC_WBXML_END         0x01
#define MAILACTIVESYNC_WBXML_ENTITY      0x02
#define MAILACTIVESYNC_WBXML_STR_I       0x03
#define MAILACTIVESYNC_WBXML_LITERAL     0x04
#define MAILACTIVESYNC_WBXML_STR_T       0x83
#define MAILACTIVESYNC_WBXML_OPAQUE      0xC3

#define MAILACTIVESYNC_WBXML_HAS_CONTENT 0x40
#define MAILACTIVESYNC_WBXML_HAS_ATTRS   0x80
#define MAILACTIVESYNC_WBXML_TOKEN_MASK  0x3F

#define MAILACTIVESYNC_WBXML_VERSION     0x03
#define MAILACTIVESYNC_WBXML_PUBLIC_ID   0x01
#define MAILACTIVESYNC_WBXML_CHARSET     0x6A

enum {
  MAILACTIVESYNC_CP_AIRSYNC = 0,
  MAILACTIVESYNC_CP_EMAIL = 2,
  MAILACTIVESYNC_CP_MOVE = 5,
  MAILACTIVESYNC_CP_GETITEMESTIMATE = 6,
  MAILACTIVESYNC_CP_FOLDERHIERARCHY = 7,
  MAILACTIVESYNC_CP_RESOLVERECIPIENTS = 10,
  MAILACTIVESYNC_CP_VALIDATECERT = 11,
  MAILACTIVESYNC_CP_PING = 13,
  MAILACTIVESYNC_CP_PROVISION = 14,
  MAILACTIVESYNC_CP_SEARCH = 15,
  MAILACTIVESYNC_CP_AIRSYNCBASE = 17,
  MAILACTIVESYNC_CP_SETTINGS = 18,
  MAILACTIVESYNC_CP_ITEMOPERATIONS = 20,
  MAILACTIVESYNC_CP_COMPOSEMAIL = 21,
  MAILACTIVESYNC_CP_EMAIL2 = 22,
  MAILACTIVESYNC_CP_RIGHTSMANAGEMENT = 24,
  MAILACTIVESYNC_CP_FIND = 25
};

enum {
  MAILACTIVESYNC_AIRSYNC_SYNC = 0x05,
  MAILACTIVESYNC_AIRSYNC_RESPONSES = 0x06,
  MAILACTIVESYNC_AIRSYNC_ADD = 0x07,
  MAILACTIVESYNC_AIRSYNC_CHANGE = 0x08,
  MAILACTIVESYNC_AIRSYNC_DELETE = 0x09,
  MAILACTIVESYNC_AIRSYNC_FETCH = 0x0A,
  MAILACTIVESYNC_AIRSYNC_SYNC_KEY = 0x0B,
  MAILACTIVESYNC_AIRSYNC_CLIENT_ID = 0x0C,
  MAILACTIVESYNC_AIRSYNC_SERVER_ID = 0x0D,
  MAILACTIVESYNC_AIRSYNC_STATUS = 0x0E,
  MAILACTIVESYNC_AIRSYNC_COLLECTION = 0x0F,
  MAILACTIVESYNC_AIRSYNC_CLASS = 0x10,
  MAILACTIVESYNC_AIRSYNC_COLLECTION_ID = 0x12,
  MAILACTIVESYNC_AIRSYNC_GET_CHANGES = 0x13,
  MAILACTIVESYNC_AIRSYNC_MORE_AVAILABLE = 0x14,
  MAILACTIVESYNC_AIRSYNC_WINDOW_SIZE = 0x15,
  MAILACTIVESYNC_AIRSYNC_COMMANDS = 0x16,
  MAILACTIVESYNC_AIRSYNC_OPTIONS = 0x17,
  MAILACTIVESYNC_AIRSYNC_FILTER_TYPE = 0x18,
  MAILACTIVESYNC_AIRSYNC_CONFLICT = 0x1B,
  MAILACTIVESYNC_AIRSYNC_COLLECTIONS = 0x1C,
  MAILACTIVESYNC_AIRSYNC_APPLICATION_DATA = 0x1D,
  MAILACTIVESYNC_AIRSYNC_DELETES_AS_MOVES = 0x1E,
  MAILACTIVESYNC_AIRSYNC_SUPPORTED = 0x20,
  MAILACTIVESYNC_AIRSYNC_SOFT_DELETE = 0x21,
  MAILACTIVESYNC_AIRSYNC_MIME_SUPPORT = 0x22,
  MAILACTIVESYNC_AIRSYNC_MIME_TRUNCATION = 0x23,
  MAILACTIVESYNC_AIRSYNC_WAIT = 0x24,
  MAILACTIVESYNC_AIRSYNC_LIMIT = 0x25,
  MAILACTIVESYNC_AIRSYNC_PARTIAL = 0x26,
  MAILACTIVESYNC_AIRSYNC_CONVERSATION_MODE = 0x27,
  MAILACTIVESYNC_AIRSYNC_MAX_ITEMS = 0x28,
  MAILACTIVESYNC_AIRSYNC_HEARTBEAT_INTERVAL = 0x29
};

enum {
  MAILACTIVESYNC_EMAIL_BODY = 0x0C,
  MAILACTIVESYNC_EMAIL_BODY_SIZE = 0x0D,
  MAILACTIVESYNC_EMAIL_BODY_TRUNCATED = 0x0E,
  MAILACTIVESYNC_EMAIL_DATE_RECEIVED = 0x0F,
  MAILACTIVESYNC_EMAIL_DISPLAY_TO = 0x11,
  MAILACTIVESYNC_EMAIL_IMPORTANCE = 0x12,
  MAILACTIVESYNC_EMAIL_MESSAGE_CLASS = 0x13,
  MAILACTIVESYNC_EMAIL_SUBJECT = 0x14,
  MAILACTIVESYNC_EMAIL_READ = 0x15,
  MAILACTIVESYNC_EMAIL_TO = 0x16,
  MAILACTIVESYNC_EMAIL_CC = 0x17,
  MAILACTIVESYNC_EMAIL_FROM = 0x18,
  MAILACTIVESYNC_EMAIL_REPLY_TO = 0x19,
  MAILACTIVESYNC_EMAIL_TIME_ZONE = 0x1A,
  MAILACTIVESYNC_EMAIL_CATEGORIES = 0x1B,
  MAILACTIVESYNC_EMAIL_CATEGORY = 0x1C,
  MAILACTIVESYNC_EMAIL_THREAD_TOPIC = 0x35,
  MAILACTIVESYNC_EMAIL_MIME_DATA = 0x36,
  MAILACTIVESYNC_EMAIL_MIME_TRUNCATED = 0x37,
  MAILACTIVESYNC_EMAIL_MIME_SIZE = 0x38,
  MAILACTIVESYNC_EMAIL_INTERNET_CPID = 0x39,
  MAILACTIVESYNC_EMAIL_FLAG = 0x3A,
  MAILACTIVESYNC_EMAIL_STATUS = 0x3B,
  MAILACTIVESYNC_EMAIL_CONTENT_CLASS = 0x3C,
  MAILACTIVESYNC_EMAIL_FLAG_TYPE = 0x3D,
  MAILACTIVESYNC_EMAIL_COMPLETE_TIME = 0x3E
};

enum {
  MAILACTIVESYNC_EMAIL2_CONVERSATION_ID = 0x09,
  MAILACTIVESYNC_EMAIL2_CONVERSATION_INDEX = 0x0A,
  MAILACTIVESYNC_EMAIL2_IS_DRAFT = 0x14,
  MAILACTIVESYNC_EMAIL2_BCC = 0x15,
  MAILACTIVESYNC_EMAIL2_SEND = 0x16
};

enum {
  MAILACTIVESYNC_MOVE_MOVE_ITEMS = 0x05,
  MAILACTIVESYNC_MOVE_MOVES = 0x05,
  MAILACTIVESYNC_MOVE_MOVE = 0x06,
  MAILACTIVESYNC_MOVE_SRCMSGID = 0x07,
  MAILACTIVESYNC_MOVE_SRCFLDID = 0x08,
  MAILACTIVESYNC_MOVE_DSTFLDID = 0x09,
  MAILACTIVESYNC_MOVE_RESPONSE = 0x0A,
  MAILACTIVESYNC_MOVE_STATUS = 0x0B,
  MAILACTIVESYNC_MOVE_DSTMSGID = 0x0C
};

enum {
  MAILACTIVESYNC_GETITEMESTIMATE_GET_ITEM_ESTIMATE = 0x05,
  MAILACTIVESYNC_GETITEMESTIMATE_VERSION = 0x06,
  MAILACTIVESYNC_GETITEMESTIMATE_COLLECTIONS = 0x07,
  MAILACTIVESYNC_GETITEMESTIMATE_COLLECTION = 0x08,
  MAILACTIVESYNC_GETITEMESTIMATE_CLASS = 0x09,
  MAILACTIVESYNC_GETITEMESTIMATE_COLLECTION_ID = 0x0A,
  MAILACTIVESYNC_GETITEMESTIMATE_DATE_TIME = 0x0B,
  MAILACTIVESYNC_GETITEMESTIMATE_ESTIMATE = 0x0C,
  MAILACTIVESYNC_GETITEMESTIMATE_RESPONSE = 0x0D,
  MAILACTIVESYNC_GETITEMESTIMATE_STATUS = 0x0E
};

enum {
  MAILACTIVESYNC_FOLDER_DISPLAY_NAME = 0x07,
  MAILACTIVESYNC_FOLDER_SERVER_ID = 0x08,
  MAILACTIVESYNC_FOLDER_PARENT_ID = 0x09,
  MAILACTIVESYNC_FOLDER_TYPE = 0x0A,
  MAILACTIVESYNC_FOLDER_STATUS = 0x0C,
  MAILACTIVESYNC_FOLDER_CHANGES = 0x0E,
  MAILACTIVESYNC_FOLDER_ADD = 0x0F,
  MAILACTIVESYNC_FOLDER_DELETE = 0x10,
  MAILACTIVESYNC_FOLDER_UPDATE = 0x11,
  MAILACTIVESYNC_FOLDER_SYNC_KEY = 0x12,
  MAILACTIVESYNC_FOLDER_FOLDER_CREATE = 0x13,
  MAILACTIVESYNC_FOLDER_FOLDER_DELETE = 0x14,
  MAILACTIVESYNC_FOLDER_FOLDER_UPDATE = 0x15,
  MAILACTIVESYNC_FOLDER_FOLDER_SYNC = 0x16,
  MAILACTIVESYNC_FOLDER_COUNT = 0x17
};

enum {
  MAILACTIVESYNC_RESOLVERECIPIENTS_RESOLVE_RECIPIENTS = 0x05,
  MAILACTIVESYNC_RESOLVERECIPIENTS_RESPONSE = 0x06,
  MAILACTIVESYNC_RESOLVERECIPIENTS_STATUS = 0x07,
  MAILACTIVESYNC_RESOLVERECIPIENTS_TYPE = 0x08,
  MAILACTIVESYNC_RESOLVERECIPIENTS_RECIPIENT = 0x09,
  MAILACTIVESYNC_RESOLVERECIPIENTS_DISPLAY_NAME = 0x0A,
  MAILACTIVESYNC_RESOLVERECIPIENTS_EMAIL_ADDRESS = 0x0B,
  MAILACTIVESYNC_RESOLVERECIPIENTS_CERTIFICATES = 0x0C,
  MAILACTIVESYNC_RESOLVERECIPIENTS_CERTIFICATE = 0x0D,
  MAILACTIVESYNC_RESOLVERECIPIENTS_MINI_CERTIFICATE = 0x0E,
  MAILACTIVESYNC_RESOLVERECIPIENTS_OPTIONS = 0x0F,
  MAILACTIVESYNC_RESOLVERECIPIENTS_TO = 0x10,
  MAILACTIVESYNC_RESOLVERECIPIENTS_CERTIFICATE_RETRIEVAL = 0x11,
  MAILACTIVESYNC_RESOLVERECIPIENTS_RECIPIENT_COUNT = 0x12,
  MAILACTIVESYNC_RESOLVERECIPIENTS_MAX_CERTIFICATES = 0x13,
  MAILACTIVESYNC_RESOLVERECIPIENTS_MAX_AMBIGUOUS_RECIPIENTS = 0x14,
  MAILACTIVESYNC_RESOLVERECIPIENTS_CERTIFICATE_COUNT = 0x15
};

enum {
  MAILACTIVESYNC_VALIDATECERT_VALIDATE_CERT = 0x05,
  MAILACTIVESYNC_VALIDATECERT_CERTIFICATES = 0x06,
  MAILACTIVESYNC_VALIDATECERT_CERTIFICATE = 0x07,
  MAILACTIVESYNC_VALIDATECERT_CERTIFICATE_CHAIN = 0x08,
  MAILACTIVESYNC_VALIDATECERT_CHECK_CRL = 0x09,
  MAILACTIVESYNC_VALIDATECERT_STATUS = 0x0A
};

enum {
  MAILACTIVESYNC_PING_PING = 0x05,
  MAILACTIVESYNC_PING_STATUS = 0x07,
  MAILACTIVESYNC_PING_HEARTBEAT_INTERVAL = 0x08,
  MAILACTIVESYNC_PING_FOLDERS = 0x09,
  MAILACTIVESYNC_PING_FOLDER = 0x0A,
  MAILACTIVESYNC_PING_ID = 0x0B,
  MAILACTIVESYNC_PING_CLASS = 0x0C,
  MAILACTIVESYNC_PING_MAX_FOLDERS = 0x0D
};

enum {
  MAILACTIVESYNC_PROVISION_PROVISION = 0x05,
  MAILACTIVESYNC_PROVISION_POLICIES = 0x06,
  MAILACTIVESYNC_PROVISION_POLICY = 0x07,
  MAILACTIVESYNC_PROVISION_POLICY_TYPE = 0x08,
  MAILACTIVESYNC_PROVISION_POLICY_KEY = 0x09,
  MAILACTIVESYNC_PROVISION_DATA = 0x0A,
  MAILACTIVESYNC_PROVISION_STATUS = 0x0B,
  MAILACTIVESYNC_PROVISION_REMOTE_WIPE = 0x0C,
  MAILACTIVESYNC_PROVISION_EAS_PROVISION_DOC = 0x0D
};

enum {
  MAILACTIVESYNC_SEARCH_SEARCH = 0x05,
  MAILACTIVESYNC_SEARCH_STORE = 0x07,
  MAILACTIVESYNC_SEARCH_NAME = 0x08,
  MAILACTIVESYNC_SEARCH_QUERY = 0x09,
  MAILACTIVESYNC_SEARCH_OPTIONS = 0x0A,
  MAILACTIVESYNC_SEARCH_RANGE = 0x0B,
  MAILACTIVESYNC_SEARCH_STATUS = 0x0C,
  MAILACTIVESYNC_SEARCH_RESPONSE = 0x0D,
  MAILACTIVESYNC_SEARCH_RESULT = 0x0E,
  MAILACTIVESYNC_SEARCH_PROPERTIES = 0x0F,
  MAILACTIVESYNC_SEARCH_TOTAL = 0x10,
  MAILACTIVESYNC_SEARCH_EQUAL_TO = 0x11,
  MAILACTIVESYNC_SEARCH_VALUE = 0x12,
  MAILACTIVESYNC_SEARCH_AND = 0x13,
  MAILACTIVESYNC_SEARCH_OR = 0x14,
  MAILACTIVESYNC_SEARCH_FREE_TEXT = 0x15,
  MAILACTIVESYNC_SEARCH_DEEP_TRAVERSAL = 0x17,
  MAILACTIVESYNC_SEARCH_LONG_ID = 0x18,
  MAILACTIVESYNC_SEARCH_REBUILD_RESULTS = 0x19,
  MAILACTIVESYNC_SEARCH_LESS_THAN = 0x1A,
  MAILACTIVESYNC_SEARCH_GREATER_THAN = 0x1B,
  MAILACTIVESYNC_SEARCH_USER_NAME = 0x1E,
  MAILACTIVESYNC_SEARCH_PASSWORD = 0x1F,
  MAILACTIVESYNC_SEARCH_CONVERSATION_ID = 0x20
};

enum {
  MAILACTIVESYNC_FIND_FIND = 0x05,
  MAILACTIVESYNC_FIND_SEARCH_ID = 0x06,
  MAILACTIVESYNC_FIND_EXECUTE_SEARCH = 0x07,
  MAILACTIVESYNC_FIND_MAILBOX_SEARCH_CRITERION = 0x08,
  MAILACTIVESYNC_FIND_QUERY = 0x09,
  MAILACTIVESYNC_FIND_STATUS = 0x0A,
  MAILACTIVESYNC_FIND_FREE_TEXT = 0x0B,
  MAILACTIVESYNC_FIND_OPTIONS = 0x0C,
  MAILACTIVESYNC_FIND_RANGE = 0x0D,
  MAILACTIVESYNC_FIND_DEEP_TRAVERSAL = 0x0E,
  MAILACTIVESYNC_FIND_RESPONSE = 0x11,
  MAILACTIVESYNC_FIND_RESULT = 0x12,
  MAILACTIVESYNC_FIND_PROPERTIES = 0x13,
  MAILACTIVESYNC_FIND_PREVIEW = 0x14,
  MAILACTIVESYNC_FIND_HAS_ATTACHMENTS = 0x15,
  MAILACTIVESYNC_FIND_TOTAL = 0x16,
  MAILACTIVESYNC_FIND_DISPLAY_CC = 0x17,
  MAILACTIVESYNC_FIND_DISPLAY_BCC = 0x18
};

enum {
  MAILACTIVESYNC_AIRSYNCBASE_BODY_PREFERENCE = 0x05,
  MAILACTIVESYNC_AIRSYNCBASE_TYPE = 0x06,
  MAILACTIVESYNC_AIRSYNCBASE_TRUNCATION_SIZE = 0x07,
  MAILACTIVESYNC_AIRSYNCBASE_ALL_OR_NONE = 0x08,
  MAILACTIVESYNC_AIRSYNCBASE_BODY = 0x0A,
  MAILACTIVESYNC_AIRSYNCBASE_DATA = 0x0B,
  MAILACTIVESYNC_AIRSYNCBASE_ESTIMATED_DATA_SIZE = 0x0C,
  MAILACTIVESYNC_AIRSYNCBASE_TRUNCATED = 0x0D,
  MAILACTIVESYNC_AIRSYNCBASE_ATTACHMENTS = 0x0E,
  MAILACTIVESYNC_AIRSYNCBASE_ATTACHMENT = 0x0F,
  MAILACTIVESYNC_AIRSYNCBASE_DISPLAY_NAME = 0x10,
  MAILACTIVESYNC_AIRSYNCBASE_FILE_REFERENCE = 0x11,
  MAILACTIVESYNC_AIRSYNCBASE_METHOD = 0x12,
  MAILACTIVESYNC_AIRSYNCBASE_CONTENT_ID = 0x13,
  MAILACTIVESYNC_AIRSYNCBASE_CONTENT_LOCATION = 0x14,
  MAILACTIVESYNC_AIRSYNCBASE_IS_INLINE = 0x15,
  MAILACTIVESYNC_AIRSYNCBASE_NATIVE_BODY_TYPE = 0x16,
  MAILACTIVESYNC_AIRSYNCBASE_CONTENT_TYPE = 0x17,
  MAILACTIVESYNC_AIRSYNCBASE_PREVIEW = 0x18,
  MAILACTIVESYNC_AIRSYNCBASE_BODY_PART_PREFERENCE = 0x19,
  MAILACTIVESYNC_AIRSYNCBASE_BODY_PART = 0x1A,
  MAILACTIVESYNC_AIRSYNCBASE_STATUS = 0x1B,
  MAILACTIVESYNC_AIRSYNCBASE_ADD = 0x1C,
  MAILACTIVESYNC_AIRSYNCBASE_DELETE = 0x1D,
  MAILACTIVESYNC_AIRSYNCBASE_CLIENT_ID = 0x1E,
  MAILACTIVESYNC_AIRSYNCBASE_CONTENT = 0x1F
};

enum {
  MAILACTIVESYNC_SETTINGS_SETTINGS = 0x05,
  MAILACTIVESYNC_SETTINGS_STATUS = 0x06,
  MAILACTIVESYNC_SETTINGS_GET = 0x07,
  MAILACTIVESYNC_SETTINGS_SET = 0x08,
  MAILACTIVESYNC_SETTINGS_DEVICE_INFORMATION = 0x16,
  MAILACTIVESYNC_SETTINGS_MODEL = 0x17,
  MAILACTIVESYNC_SETTINGS_IMEI = 0x18,
  MAILACTIVESYNC_SETTINGS_FRIENDLY_NAME = 0x19,
  MAILACTIVESYNC_SETTINGS_OS = 0x1A,
  MAILACTIVESYNC_SETTINGS_OS_LANGUAGE = 0x1B,
  MAILACTIVESYNC_SETTINGS_PHONE_NUMBER = 0x1C,
  MAILACTIVESYNC_SETTINGS_USER_INFORMATION = 0x1D,
  MAILACTIVESYNC_SETTINGS_EMAIL_ADDRESSES = 0x1E,
  MAILACTIVESYNC_SETTINGS_SMTP_ADDRESS = 0x1F,
  MAILACTIVESYNC_SETTINGS_USER_AGENT = 0x20,
  MAILACTIVESYNC_SETTINGS_ENABLE_OUTBOUND_SMS = 0x21,
  MAILACTIVESYNC_SETTINGS_MOBILE_OPERATOR = 0x22,
  MAILACTIVESYNC_SETTINGS_PRIMARY_SMTP_ADDRESS = 0x23,
  MAILACTIVESYNC_SETTINGS_ACCOUNTS = 0x24,
  MAILACTIVESYNC_SETTINGS_ACCOUNT = 0x25,
  MAILACTIVESYNC_SETTINGS_ACCOUNT_ID = 0x26,
  MAILACTIVESYNC_SETTINGS_ACCOUNT_NAME = 0x27,
  MAILACTIVESYNC_SETTINGS_USER_DISPLAY_NAME = 0x28,
  MAILACTIVESYNC_SETTINGS_SEND_DISABLED = 0x29
};

enum {
  MAILACTIVESYNC_ITEMOPERATIONS_ITEM_OPERATIONS = 0x05,
  MAILACTIVESYNC_ITEMOPERATIONS_FETCH = 0x06,
  MAILACTIVESYNC_ITEMOPERATIONS_STORE = 0x07,
  MAILACTIVESYNC_ITEMOPERATIONS_OPTIONS = 0x08,
  MAILACTIVESYNC_ITEMOPERATIONS_RANGE = 0x09,
  MAILACTIVESYNC_ITEMOPERATIONS_TOTAL = 0x0A,
  MAILACTIVESYNC_ITEMOPERATIONS_PROPERTIES = 0x0B,
  MAILACTIVESYNC_ITEMOPERATIONS_DATA = 0x0C,
  MAILACTIVESYNC_ITEMOPERATIONS_STATUS = 0x0D,
  MAILACTIVESYNC_ITEMOPERATIONS_RESPONSE = 0x0E,
  MAILACTIVESYNC_ITEMOPERATIONS_VERSION = 0x0F,
  MAILACTIVESYNC_ITEMOPERATIONS_SCHEMA = 0x10,
  MAILACTIVESYNC_ITEMOPERATIONS_PART = 0x11,
  MAILACTIVESYNC_ITEMOPERATIONS_EMPTY_FOLDER_CONTENTS = 0x12,
  MAILACTIVESYNC_ITEMOPERATIONS_DELETE_SUB_FOLDERS = 0x13,
  MAILACTIVESYNC_ITEMOPERATIONS_MOVE = 0x16,
  MAILACTIVESYNC_ITEMOPERATIONS_DSTFLDID = 0x17
};

enum {
  MAILACTIVESYNC_COMPOSEMAIL_SEND_MAIL = 0x05,
  MAILACTIVESYNC_COMPOSEMAIL_SMART_FORWARD = 0x06,
  MAILACTIVESYNC_COMPOSEMAIL_SMART_REPLY = 0x07,
  MAILACTIVESYNC_COMPOSEMAIL_SAVE_IN_SENT_ITEMS = 0x08,
  MAILACTIVESYNC_COMPOSEMAIL_REPLACE_MIME = 0x09,
  MAILACTIVESYNC_COMPOSEMAIL_SOURCE = 0x0B,
  MAILACTIVESYNC_COMPOSEMAIL_FOLDER_ID = 0x0C,
  MAILACTIVESYNC_COMPOSEMAIL_ITEM_ID = 0x0D,
  MAILACTIVESYNC_COMPOSEMAIL_LONG_ID = 0x0E,
  MAILACTIVESYNC_COMPOSEMAIL_INSTANCE_ID = 0x0F,
  MAILACTIVESYNC_COMPOSEMAIL_MIME = 0x10,
  MAILACTIVESYNC_COMPOSEMAIL_CLIENT_ID = 0x11,
  MAILACTIVESYNC_COMPOSEMAIL_STATUS = 0x12,
  MAILACTIVESYNC_COMPOSEMAIL_ACCOUNT_ID = 0x13
};

enum {
  MAILACTIVESYNC_RIGHTSMANAGEMENT_RIGHTS_MANAGEMENT_SUPPORT = 0x05
};

struct mailactivesync_wbxml_token_info {
  uint8_t code_page;
  uint8_t token;
  const char * name;
};

const char * mailactivesync_wbxml_tag_name(uint8_t code_page,
    uint8_t token);

int mailactivesync_wbxml_tag_lookup(const char * name,
    uint8_t * code_page,
    uint8_t * token);

#ifdef __cplusplus
}
#endif

#endif
