#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "mailmime.h"
#include "mailmime_write_file.h"
#include "mime_builder_helpers.h"
#include "test_utils.h"

static struct mailmime * build_message1(void)
{
  struct mailmime * alternative;

  alternative = mime_builder_new_part(MAILMIME_MULTIPLE,
      "multipart/alternative; boundary=\"1\"", NULL);
  mime_builder_add_part(alternative,
      mime_builder_new_text_part("text/plain; charset=\"utf-8\"",
          MAILMIME_MECHANISM_7BIT, "This is a HTML content"));
  mime_builder_add_part(alternative,
      mime_builder_new_text_part("text/html; charset=\"utf-8\"",
          MAILMIME_MECHANISM_QUOTED_PRINTABLE,
          "<html><body>This is a HTML content</body></html>"));
  return mime_builder_wrap_message(alternative, "testMessageBuilder1", 0);
}

static struct mailmime * build_message2(void)
{
  struct mailmime * mixed;
  struct mailmime * alternative;

  mixed = mime_builder_new_part(MAILMIME_MULTIPLE,
      "multipart/mixed; boundary=\"2\"", NULL);
  alternative = mime_builder_new_part(MAILMIME_MULTIPLE,
      "multipart/alternative; boundary=\"1\"", NULL);
  mime_builder_add_part(alternative,
      mime_builder_new_text_part("text/plain; charset=\"utf-8\"",
          MAILMIME_MECHANISM_7BIT, "This is a HTML content"));
  mime_builder_add_part(alternative,
      mime_builder_new_text_part("text/html; charset=\"utf-8\"",
          MAILMIME_MECHANISM_QUOTED_PRINTABLE,
          "<html><body>This is a HTML content</body></html>"));
  mime_builder_add_part(mixed, alternative);
  mime_builder_add_part(mixed,
      mime_builder_new_attachment_part("data/input/photo.jpg", NULL));
  mime_builder_add_part(mixed,
      mime_builder_new_attachment_part("data/input/photo2.jpg", NULL));
  return mime_builder_wrap_message(mixed, "testMessageBuilder2", 1);
}

static struct mailmime * build_message3(void)
{
  struct mailmime * mixed;
  struct mailmime * alternative;
  struct mailmime * related;

  mixed = mime_builder_new_part(MAILMIME_MULTIPLE,
      "multipart/mixed; boundary=\"3\"", NULL);
  alternative = mime_builder_new_part(MAILMIME_MULTIPLE,
      "multipart/alternative; boundary=\"2\"", NULL);
  related = mime_builder_new_part(MAILMIME_MULTIPLE,
      "multipart/related; boundary=\"1\"", NULL);

  mime_builder_add_part(alternative,
      mime_builder_new_text_part("text/plain; charset=\"utf-8\"",
          MAILMIME_MECHANISM_7BIT, "This is a HTML content\r\n\r\n"));
  mime_builder_add_part(related,
      mime_builder_new_text_part("text/html; charset=\"utf-8\"",
          MAILMIME_MECHANISM_QUOTED_PRINTABLE,
          "<html><body><div>This is a HTML content</div><div><img "
          "src=\"cid:123\"></div></body></html>"));
  mime_builder_add_part(related,
      mime_builder_new_attachment_part("data/input/photo2.jpg", "123"));
  mime_builder_add_part(alternative, related);
  mime_builder_add_part(mixed, alternative);
  mime_builder_add_part(mixed,
      mime_builder_new_attachment_part("data/input/photo.jpg", NULL));
  return mime_builder_wrap_message(mixed, "testMessageBuilder3", 1);
}

static char * write_mime_to_memory(struct mailmime * mime, size_t * length)
{
  FILE * f;
  char * data;
  long size;
  int col = 0;
  int r;

  f = tmpfile();
  assert(f != NULL);

  r = mailmime_write_file(f, &col, mime);
  assert(r == MAILIMF_NO_ERROR);
  assert(fflush(f) == 0);

  size = ftell(f);
  assert(size >= 0);
  assert(fseek(f, 0, SEEK_SET) == 0);

  data = malloc((size_t) size + 1);
  assert(data != NULL);
  assert(fread(data, 1, (size_t) size, f) == (size_t) size);
  data[size] = '\0';
  fclose(f);

  *length = (size_t) size;
  return data;
}

static void assert_message_equals_fixture(const char * name,
    struct mailmime * message, const char * expected_path)
{
  char * expected;
  char * generated;
  size_t expected_length;
  size_t generated_length;

  expected = test_read_file(expected_path, &expected_length);
  generated = write_mime_to_memory(message, &generated_length);
  if (generated_length != expected_length ||
      memcmp(generated, expected, expected_length) != 0) {
    size_t i;
    size_t min_len = generated_length < expected_length ?
        generated_length : expected_length;

    for (i = 0; i < min_len; i++) {
      if (generated[i] != expected[i])
        break;
    }
    fprintf(stderr,
        "mime-builder: %s mailmime_write_file() output differs from %s "
        "at byte %lu (generated length %lu, expected length %lu)\n",
        name, expected_path, (unsigned long) i,
        (unsigned long) generated_length, (unsigned long) expected_length);
    if (i < min_len) {
      fprintf(stderr, "generated byte 0x%02x, expected byte 0x%02x\n",
          (unsigned char) generated[i], (unsigned char) expected[i]);
    }
    abort();
  }

  free(generated);
  free(expected);
}

int main(void)
{
  struct mailmime * message;

  puts("testMessageBuilder1");
  message = build_message1();
  assert_message_equals_fixture("testMessageBuilder1", message,
      "data/output/builder1.eml");
  mailmime_free(message);

  puts("testMessageBuilder2");
  message = build_message2();
  assert_message_equals_fixture("testMessageBuilder2", message,
      "data/output/builder2.eml");
  mailmime_free(message);

  puts("testMessageBuilder3");
  message = build_message3();
  assert_message_equals_fixture("testMessageBuilder3", message,
      "data/output/builder3.eml");
  mailmime_free(message);

  puts("mime_builder_test: 3 messages matched mailmime_write_file() output");
  return 0;
}
