/*
 * libEtPan! -- a mail stuff library
 *
 * Copyright (C) 2001, 2005 - DINH Viet Hoa
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the libEtPan! project nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*
 * $Id: libetpan.h,v 1.17 2007/01/18 09:15:02 hoa Exp $
 */

#ifndef LIBETPAN_H

#define LIBETPAN_H

#ifdef __cplusplus
extern "C" {
#endif
/* Public headers: generated by tools/public_headers.py. */

/* . */
#include <libetpan/libetpan-config.h>

/* src/data-types */
#include <libetpan/carray.h>
#include <libetpan/charconv.h>
#include <libetpan/chash.h>
#include <libetpan/clist.h>
#include <libetpan/mailjson.h>
#include <libetpan/mailhttp.h>
#include <libetpan/mailsem.h>
#include <libetpan/mailstream.h>
#include <libetpan/mailstream_cfstream.h>
#include <libetpan/mailstream_helper.h>
#include <libetpan/mailstream_low.h>
#include <libetpan/mailstream_socket.h>
#include <libetpan/mailstream_ssl.h>
#include <libetpan/mailstream_types.h>
#include <libetpan/mmapstring.h>

/* src/driver/implementation/db */
#include <libetpan/dbstorage.h>

/* src/driver/implementation/feed */
#include <libetpan/feedstorage.h>

/* src/driver/implementation/hotmail */
#include <libetpan/hotmailstorage.h>

/* src/driver/implementation/imap */
#include <libetpan/imapstorage.h>

/* src/driver/implementation/maildir */
#include <libetpan/maildirstorage.h>

/* src/driver/implementation/mbox */
#include <libetpan/mboxstorage.h>

/* src/driver/implementation/mh */
#include <libetpan/mhstorage.h>

/* src/driver/implementation/nntp */
#include <libetpan/nntpstorage.h>

/* src/driver/implementation/pop3 */
#include <libetpan/pop3storage.h>

/* src/driver/interface */
#include <libetpan/maildriver_errors.h>
#include <libetpan/maildriver_types.h>
#include <libetpan/mailfolder.h>
#include <libetpan/mailmessage.h>
#include <libetpan/mailmessage_types.h>
#include <libetpan/mailstorage.h>
#include <libetpan/mailstorage_types.h>

/* src/driver/tools */
#include <libetpan/mailthread.h>
#include <libetpan/mailthread_types.h>

/* src/engine */
#include <libetpan/mailengine.h>
#include <libetpan/mailprivacy.h>
#include <libetpan/mailprivacy_gnupg.h>
#include <libetpan/mailprivacy_smime.h>
#include <libetpan/mailprivacy_tools.h>
#include <libetpan/mailprivacy_types.h>

/* src/low-level/activesync */
#include <libetpan/mailactivesync.h>
#include <libetpan/mailactivesync_http.h>
#include <libetpan/mailactivesync_types.h>

/* src/low-level/gmail */
#include <libetpan/mailgmail.h>
#include <libetpan/mailgmail_types.h>

/* src/low-level/imap */
#include <libetpan/acl.h>
#include <libetpan/acl_types.h>
#include <libetpan/annotatemore.h>
#include <libetpan/annotatemore_types.h>
#include <libetpan/clientid.h>
#include <libetpan/condstore.h>
#include <libetpan/condstore_types.h>
#include <libetpan/enable.h>
#include <libetpan/idle.h>
#include <libetpan/mailimap.h>
#include <libetpan/mailimap_compress.h>
#include <libetpan/mailimap_extension.h>
#include <libetpan/mailimap_extension_types.h>
#include <libetpan/mailimap_helper.h>
#include <libetpan/mailimap_id.h>
#include <libetpan/mailimap_id_types.h>
#include <libetpan/mailimap_oauth2.h>
#include <libetpan/mailimap_parser_hack.h>
#include <libetpan/mailimap_socket.h>
#include <libetpan/mailimap_sort.h>
#include <libetpan/mailimap_sort_types.h>
#include <libetpan/mailimap_ssl.h>
#include <libetpan/mailimap_types.h>
#include <libetpan/mailimap_types_helper.h>
#include <libetpan/namespace.h>
#include <libetpan/namespace_types.h>
#include <libetpan/qresync.h>
#include <libetpan/qresync_types.h>
#include <libetpan/quota.h>
#include <libetpan/quota_types.h>
#include <libetpan/uidplus.h>
#include <libetpan/uidplus_types.h>
#include <libetpan/xgmlabels.h>
#include <libetpan/xgmmsgid.h>
#include <libetpan/xgmthrid.h>
#include <libetpan/xlist.h>

/* src/low-level/imf */
#include <libetpan/mailimf.h>
#include <libetpan/mailimf_types.h>
#include <libetpan/mailimf_types_helper.h>
#include <libetpan/mailimf_write_file.h>
#include <libetpan/mailimf_write_generic.h>
#include <libetpan/mailimf_write_mem.h>

/* src/low-level/jmap */
#if defined(HAVE_JMAP) || (defined(LIBETPAN_HAS_JMAP) && LIBETPAN_HAS_JMAP)
#include <libetpan/mailjmap.h>
#include <libetpan/mailjmap_blob.h>
#include <libetpan/mailjmap_http.h>
#include <libetpan/mailjmap_mail.h>
#include <libetpan/mailjmap_request.h>
#include <libetpan/mailjmap_response.h>
#include <libetpan/mailjmap_types.h>
#endif

/* src/low-level/mime */
#include <libetpan/mailmime.h>
#include <libetpan/mailmime_content.h>
#include <libetpan/mailmime_decode.h>
#include <libetpan/mailmime_disposition.h>
#include <libetpan/mailmime_types.h>
#include <libetpan/mailmime_types_helper.h>
#include <libetpan/mailmime_write_file.h>
#include <libetpan/mailmime_write_generic.h>
#include <libetpan/mailmime_write_mem.h>

/* src/low-level/nntp */
#include <libetpan/newsnntp.h>
#include <libetpan/newsnntp_socket.h>
#include <libetpan/newsnntp_ssl.h>
#include <libetpan/newsnntp_types.h>

/* src/low-level/pgp */
#include <libetpan/mailpgp.h>
#include <libetpan/mailpgp_types.h>

/* src/low-level/pop3 */
#include <libetpan/mailpop3.h>
#include <libetpan/mailpop3_helper.h>
#include <libetpan/mailpop3_socket.h>
#include <libetpan/mailpop3_ssl.h>
#include <libetpan/mailpop3_types.h>

/* src/low-level/smime */
#include <libetpan/mailsmime.h>
#include <libetpan/mailsmime_types.h>

/* src/low-level/smtp */
#include <libetpan/mailsmtp.h>
#include <libetpan/mailsmtp_helper.h>
#include <libetpan/mailsmtp_oauth2.h>
#include <libetpan/mailsmtp_socket.h>
#include <libetpan/mailsmtp_ssl.h>
#include <libetpan/mailsmtp_types.h>

/* src/main */
#include <libetpan/libetpan_version.h>

/* End generated public headers. */

#ifdef __cplusplus
}
#endif

#endif
