name: Unit tests

on:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install autoconf automake cmake pkgconf m4 libtool

      - name: Prepare
        run: build-mac/bootstrap.sh

      - name: Run XCTest
        run: |
          xcodebuild test \
            -workspace build-mac/libetpan.xcworkspace \
            -scheme libetpan-unit-tests \
            -destination 'platform=macOS' \
            -derivedDataPath "$GITHUB_WORKSPACE/.build/xcode" \
            CODE_SIGNING_ALLOWED=NO

  linux:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            libtool \
            pkg-config \
            m4 \
            libsasl2-dev \
            libjson-c-dev \
            libxml2-dev \
            zlib1g-dev \
            libssl-dev \
            librnp-dev \
            libtidy-dev \
            libcurl4-openssl-dev \
            libicu-dev \
            libgnutls28-dev \
            build-essential \
            libjson-c-dev \

      - name: Configure
        run: ./autogen.sh --enable-static --enable-debug

      - name: Build
        run: make

      - name: Run unit tests
        run: make check
